### ISSUE TITLE
How to I see myself in 5 years?

### ISSUE THREAD

**Issue by mauleyzaola** [mauleyzaola/traingen#1]
Briefly explain how you imagine your life in 5 years. Family, friends, knowledge, projects, etc.

**Comment by mauleyzaola** [comment]
@mauleyzaola2 make sure to read this first: https://github.com/mauleyzaola/jstrain

**Comment by mauleyzaola2** [comment]
with more money and a job (well not a job but something that will help me to get some extra money) and some new attitude about learning

**Comment by mauleyzaola** [comment]
nice!
