### ISSUE TITLE
Watch the video and answer the questions

### ISSUE THREAD

**Issue by mauleyzaola** [mauleyzaola/traingen#10]
https://www.youtube.com/watch?v=4mLPAcYUmRU

1. How difficult do you think it is to play this song?
2. How do you think this guy learn to play the guitar so well? Was it a natural gift or discipline? How could you know that?
3. I know you've already heard this song. Which part (paste a link here within the song's timeline) do you think it is hardest to play?

**Comment by ruleyzaola** [comment]
1. very hard
2.dedicating daily,with discipline,because it happened with me in football
3.minute

**Comment by mauleyzaola** [comment]
@ruleyzaola Ru, minute is not a link. Please find out how to create a link to a youtube video on a specific time, so when you click on that link video will automatically play at tha position, not from the start.

**Comment by ruleyzaola** [comment]
https://youtu.be/4mLPAcYUmRU?t=84

**Comment by mauleyzaola** [comment]
ok closing now...
