### ISSUE TITLE
Review Raider's Cash Flow Requirements

### ISSUE THREAD

**Issue by mauleyzaola** [mauleyzaola/traingen#11]
The documentation is here: https://docs.google.com/document/d/1xDvmlbBd8wYhV30Cqkrn7FCK9Y8BAZyki40lM_alUSY/edit?usp=sharing

This is the current spreadsheets Fer is using: https://docs.google.com/spreadsheets/d/1DsMcRT-ehQzjQrJiuGfO1hbV75X3cqXWIvxoLM8kYNg/edit?usp=sharing

This is an example of the how cost are calculated: https://docs.google.com/document/d/1yGto1d8lkf5GwwUTC6GtSKRcMRCm8yKcyXa4fZ7co60/edit?usp=sharing

**Comment by mauleyzaola2** [comment]
# the raiders cash-flow

*the idea is to have all the cash movements receive and counted by the system automatically*
