### ISSUE TITLE
Install Raiders CashFlow Application

### ISSUE THREAD

**Issue by mauleyzaola** [mauleyzaola/traingen#12]
Install into a virtual machine using VirtualBox.
Instructions are here: https://github.com/mauleyzaola/raiders-cashflow/wiki/Installation

@ruleyzaola Ru, you should install this as well.

It is important that we all can run the application so we can test it and see progress as code is being developed.

**Comment by mauleyzaola2** [comment]
![image](https://cloud.githubusercontent.com/assets/13241907/9978792/8e366ac2-5f0e-11e5-9b38-abe25f17cc98.png)

**Comment by mauleyzaola2** [comment]
@mauleyzaola done daddy!
@ruleyzaola lazy bastard!

**Comment by mauleyzaola** [comment]
@ruleyzaola Ru, this is something you need to do. When you're done paste here an screenshot of the application running on the browser like @mauleyzaola2 did.
