### ISSUE TITLE
Why is it important to learn programming?

### ISSUE THREAD

**Issue by mauleyzaola** [mauleyzaola/traingen#5]
This is a simple question, so I expect simple answers. Please use https://help.github.com/articles/github-flavored-markdown/ to format text

**Comment by mauleyzaola2** [comment]
do i answer by my self or you want an explanation from the link?

**Comment by mauleyzaola** [comment]
this issue has nothing to do with the link, except that you should try to format your text a little better using github's markdown, that's what the link is about

**Comment by mauleyzaola2** [comment]
ok, thanks

**Comment by mauleyzaola2** [comment]
it makes things easy and less complicated

**Comment by mauleyzaola** [comment]
@mauleyzaola2 we are expecting to do awesome things here, but we won't do shit if we don't give awesome solutions, and your solution is :hankey: 

Really, imagine someone googles this question and gets here. Do you think he is going to say: "oh man! this is an awesome answer!"

I ask again, have you read the general guide? https://github.com/mauleyzaola/jstrain

**Comment by mauleyzaola** [comment]
and by the way, programming is complicated like hell hahaha, wtf :smile:

**Comment by mauleyzaola2** [comment]
## This is a title
### This is a subtitle
This is *italic*

**Comment by mauleyzaola2** [comment]
##hello

**Comment by mauleyzaola2** [comment]
# This is a title
### This is a subtitle
This is *italic*

**Comment by mauleyzaola2** [comment]
#2 

*it is important because it makes tasks less complicated, but to learn it is not simple you need to practice long*

**Comment by mauleyzaola2** [comment]
# why is it important

*it is important because it makes tasks less complicated and faster, but that doesn't means that it is easy to learn it*

**Comment by mauleyzaola** [comment]
that is better, not awesome
