### ISSUE TITLE
What is Node.Js and what can be done with it

### ISSUE THREAD

**Issue by mauleyzaola** [mauleyzaola/traingen#7]
Here are some findings on this subject:http://blog.teamtreehouse.com/7-awesome-things-can-build-node-js

Look for more examples, specially of those really cool that you would like to do.

**Comment by mauleyzaola2** [comment]
> my awesome way to use NODE.JS
*program a real car to move by my game console or computer as an easy way to get places*

**Comment by mauleyzaola** [comment]
This is doggyshit, please improve. Show examples of something.

**Comment by mauleyzaola2** [comment]
# what can i do?

*1. I can start backwards using previousSibling property.*
*2. We can change a node for another In a single call.*
*3. We can perform updates on the node itself.*

**Comment by mauleyzaola** [comment]
I liked the first answer better. At least it sounded more like you. Don't copy/paste like monkey please, the most important thing is to learn.
