### ISSUE TITLE
Tell me what you understood from this video

### ISSUE THREAD

**Issue by mauleyzaola** [mauleyzaola/traingen#9]
https://www.youtube.com/watch?v=Bxtb-PpZih8

**Comment by mauleyzaola2** [comment]
# what i need to do and not to do to learn faster.

*the thing with i need to start of, is to have my idea or dream of how am i going to be when i learn the thing i want to learn and stay focus about it and start moving. Next i need someone who has already made it and start learning on him, knowing of him and following him for me to have an idea of how it is. What i dont need to do is to first dont have an idol for your work, also is necesary to hear about Others people thougts about your work but it need to be from the right fount. Finally and also so important is to dedicate not a week, not a month, not a year but so much years to practice it for me to be the better at it, good at it, perfect at it and have my dream come true by my work along time.*

**Comment by mauleyzaola** [comment]
Good explanation but you forgot the most important: do not invent the wheel :smile:
